"""empty message

Revision ID: 464053b42be9
Revises: ccd30e602eea
Create Date: 2022-12-12 10:25:38.606746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464053b42be9'
down_revision = 'ccd30e602eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_filename', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('img_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('img_data')
        batch_op.drop_column('img_filename')

    # ### end Alembic commands ###
